---
- name: Zabbix Test rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: nginx is down
      condition: event.payload.trigger_name == "Nginx: Service is down"
      action:
        run_job_template:
          name: Running_nginx
          organization: Default
          job_args:
            extra_vars:
              service_name: "nginx"
